cloud:
  aws:
    credentials:
      access-key:
      secret-key: 
    region:
      static: us-east-1
    stack:
      auto: false
    dynamo-db:
      service-endpoint: dynamodb.us-east-1.amazonaws.com

application:
  bucket:
    name: sv-offersbucket

spring:
  h2:
    console:
      enabled: true

server:
  port: 9090